name: DATE upDATE

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # This checkouts the repo, otherwise folder will be empty
    # Use the version 2 so you can push back the changes
    - name: Download the repo
    - uses: actions/checkout@v2

    # Running my script. Make sure it's executable (chmod +x ./.github/script.sh)
    - name: Run the script (update the date)
      run: ./.github/script.sh

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run the program
      run: python main.py

    # Commit the changes
    - name: Commit changes
      run: |
        git config --global user.name 'Sebastian Flores'
        git config --global user.email 'sebastiandres@users.noreply.github.com'
        git commit -am "Updating the date with github actions"
        git push
